### PR TITLE
Use file context managers

### PR DESCRIPTION
**Pull request by tomers**

### CODE REVIEW

**Comment by ko-zu** [comment]
It also requires dropping Python 2.5 compatibility from core classes. Should we drop support for <2.7 now or add another compat code?

**Comment by tomers** [comment]
> Should we drop support for <2.7 now
According to https://en.wikipedia.org/wiki/History_of_Python#Table_of_versions, end of security fixes for Python 2.6 is 2013-10-29, and of Python 2.7 is 2020-01-01, so I think it is about time now to be constrained by version that is not supported for more than 6 years now.

**Comment by ko-zu** [comment]
Then we have to update respective support version etc.
Do you think this is enough to indicate dropping 2.5?
 https://github.com/ko-zu/psl/commit/35df697374053ab6bb02daf6006ef0578c3b4660 on topic branch
https://github.com/ko-zu/psl/tree/tomers-use-file-context-managers2

**Comment by tomers** [comment]
> Do you think this is enough to indicate dropping 2.5?
I think so. I've updated the PR accordingly.

**Comment by ko-zu** [comment]
Merged as commit 1f3e061a and 35df697.

**Pull request closed without merging**
